version: "3.9"

services:
  registry:
    image: docker.io/registry:2
    restart: always
    ports:
    - 5555:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: registry-realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.local.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.local.key
    volumes:
    - ./auth:/auth
    - ./data:/data
    - ./certs:/certs
