kind: Secret
apiVersion: v1
metadata:
  name: vault-cluster-backup
  namespace: ""
data:
  VAULT_ADDRESS: ""
  VAULT_TOKEN: ""
  VAULT_EXTRA_ARGS: ""
  S3_ENDPOINT: ""
  S3_ACCESS_KEY: ""
  S3_SECRET_KEY: ""
  S3_BUCKET_NAME: ""
  S3_BUCKET_PREFIX: ""
  S3_PATH_STYLE: ""
  RETENTION: ""
  MC_EXTRA_ARGS: ""

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-cluster-backup
  namespace: ""
  labels:
    jobgroup: pg-cluster-backup
spec:
  schedule: "0 1 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      name: vault-cluster-backup
      labels:
        jobgroup: vault-cluster-backup
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: vault-cluster-backup
            image: ghcr.io/this-is-tobi/tools/vault-backup:latest
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: vault-cluster-backup
          restartPolicy: Never
